# Generated by Django 4.1 on 2022-08-21 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('uid', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel_name', models.CharField(db_index=True, help_text='This refers to the title of the call e.g. Product Meeting', max_length=100)),
                ('about', models.TextField(blank=True, help_text='What is the meeting about e.g. discussion for latest product model', max_length=300, null=True)),
                ('scheld_time', models.DateTimeField(blank=True, help_text='The date and time the meeting will be held', null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('host', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the milestone', max_length=150)),
                ('info', models.TextField(blank=True, help_text='more info about the milestone', max_length=300, null=True)),
                ('duration', models.PositiveSmallIntegerField(help_text='duration of the milestone in minuites', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(5)])),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
