# Generated by Django 4.1 on 2022-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_call_host_alter_call_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
